### ISSUE TITLE
Wondering how you get mmapd_GT.csv

### ISSUE THREAD

**Issue by Haodong-Yan** [BarqueroGerman/BeLFusion#5]
I want to evaluate your code in another dataset. How can I get this file?

**Comment by BarqueroGerman** [comment]
Hi,

We didn't release the code for its computation, as such file generation should be easily reproducible.

The way it is computed was inspired in prior works (GSPS, DLow, etc.), and can be found [here](https://github.com/BarqueroGerman/BeLFusion/blob/03e9f30a7b420d0a7b6d4b4c92eb6b9168431602/metrics/evaluation.py#L109). The code simply selects multimodal futures by clustering segments with similar last observed frames (up to a threshold, which is 0.5 for H36M and 0.4 for AMASS). If the number of multimodal futures == 1, then APD = 0 in mmapd_GT.csv, and that segment APD is ignored for the APDE computation. If the number of multimodal futures > 1, then the result of computing the APD with those future poses is the value stored in "mmapg_GT.csv" for that particular segment.

PS: in an ideal scenario, we should consider the whole observation segment for the computation of the multimodal future. However, prior work simplified it because the datasets are usually not big enough to do that.

**Comment by Haodong-Yan** [comment]
Thanks for your patient explanation.
